spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ""
    username: ""
    password: "unused"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  flyway:
    clean-on-validation-error: true
    clean-disabled: false
snowflake:
  epoch: 1577822400000
messaging:
  queue:
    tasks:
      name: ""
logging:
  level:
    ROOT: INFO
