spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/noticeboard?currentSchema=noticeboard
    username: noticeboarduser
    password: noticeboardPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
