server:
  port: 8080

spring:
  datasource:
    url: ""
    username: ""
    password: ""
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"