server:
  port: 8080

spring:
  datasource:
    url: ""
    username: ""
    password: ""
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: ""
            clientSecret: ""
            scope: openid
            redirect-uri: ""
            clientName: ""
        provider:
          cognito:
            issuerUri: ""
            user-name-attribute: "cognito:username"

logging:
  level:
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
