server:
  port: 8080

spring:
  datasource:
    url: ""
    username: ""
    password: "unused" # org.postgresql.Driver expects the password to be a non-empty string. This will be replaced with value from AWS SSM.
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"