spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shipping_price}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.flyway: info