name: "1. Static Website - Deploy"
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
      STATIC_WEBSITE_HOST: ${{ secrets.STATIC_WEBSITE_HOST }}
      STATIC_WEBSITE_BUCKET_NAME: ${{ secrets.STATIC_WEBSITE_BUCKET_NAME }}
    defaults:
      run:
        working-directory: ./1-StaticWebsite/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.7"
        
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="hosted_zone_name=$HOSTED_ZONE_NAME" -var="bucket_name=$STATIC_WEBSITE_BUCKET_NAME" -var="static_website_host=$STATIC_WEBSITE_HOST"
  publish:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      STATIC_WEBSITE_BUCKET_NAME: ${{ secrets.STATIC_WEBSITE_BUCKET_NAME }}
    needs: [terraform]
    defaults:
      run:
        working-directory: ./1-StaticWebsite
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish Website
        run: |
          aws s3 sync src "s3://$STATIC_WEBSITE_BUCKET_NAME" --delete --region $AWS_DEFAULT_REGION
  test:
    runs-on: ubuntu-latest
    env:
      STATIC_WEBSITE_HOST: ${{ secrets.STATIC_WEBSITE_HOST }}
    needs: [terraform, publish]
    defaults:
      run:
        working-directory: ./1-StaticWebsite/test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - name: Run tests
        run: |
          go run test.go