name: "Static Website - Destroy"
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
      STATIC_WEBSITE_BUCKET_NAME: ${{ secrets.STATIC_WEBSITE_BUCKET_NAME }}
      STATIC_WEBSITE_HOST: ${{ secrets.STATIC_WEBSITE_HOST }}
    defaults:
      run:
        working-directory: ./1-StaticWebsite/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Empty out s3 bucket
        run: |
          aws s3 rm "s3://$STATIC_WEBSITE_BUCKET_NAME" --recursive --region $AWS_DEFAULT_REGION
  
      - name: Terraform Destroy
        run: terraform apply -auto-approve -destroy -var="hosted_zone_name=$HOSTED_ZONE_NAME" -var="bucket_name=$STATIC_WEBSITE_BUCKET_NAME" -var="static_website_host=$STATIC_WEBSITE_HOST"