name: "2. Api Gateway - Deploy"
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
      API_GATEWAY_HOST: ${{ secrets.API_GATEWAY_HOST }}
    defaults:
      run:
        working-directory: ./2-ApiGateway/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.7"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="hosted_zone_name=$HOSTED_ZONE_NAME" -var="api_gateway_host=$API_GATEWAY_HOST"
  test:
    runs-on: ubuntu-latest
    env:
      API_GATEWAY_HOST: ${{ secrets.API_GATEWAY_HOST }}
      NEUTRINO_API_KEY: ${{ secrets.NEUTRINO_API_KEY }}
      NEUTRINO_USER_ID: ${{ secrets.NEUTRINO_USER_ID }}
    needs: [terraform]
    defaults:
      run:
        working-directory: ./2-ApiGateway/test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"
      - name: Run tests
        run: |
          go run test.go
