name: "3. Simple Service - Deploy"
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./3-SimpleService/todo-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Run tests
        run: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean install
      - name: Find jar
        id: find_jar
        run: echo "EXECUTABLE_JAR_PATH=$(find `pwd -P`/target -maxdepth 1 -name '*.jar')" >> $GITHUB_OUTPUT
      - name: Upload executable jar
        uses: actions/upload-artifact@v3
        with:
          name: app.jar
          path: ${{ steps.find_jar.outputs.EXECUTABLE_JAR_PATH }}
          retention-days: 2

  terraform:
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
      SIMPLE_SERVICE_HOST: ${{ secrets.SIMPLE_SERVICE_HOST }}
      PRIVATE_KEY_OUTPUT_FILE: ./simple_service_private_key.pem
    defaults:
      run:
        working-directory: ./3-SimpleService/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: app.jar
          path: ./3-SimpleService/terraform
      - name: Find jar
        id: find_jar
        run: echo "EXECUTABLE_JAR_PATH=$(find `pwd -P` -maxdepth 1 -name '*.jar')" >> $GITHUB_OUTPUT
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.7"
      - name: Terraform Init
        run: terraform init
      - name: Terraform Deploy
        run: terraform apply -auto-approve -var="hosted_zone_name=$HOSTED_ZONE_NAME" -var="simple_service_host=$SIMPLE_SERVICE_HOST" -var="executable_jar_path=${{ steps.find_jar.outputs.EXECUTABLE_JAR_PATH }}" -var="private_key_output_file=$PRIVATE_KEY_OUTPUT_FILE"
      - name: Upload private key
        uses: actions/upload-artifact@v2
        with:
          name: simple_service_private_key.pem
          path: ./3-SimpleService/terraform/simple_service_private_key.pem
          retention-days: 2
  test:
    runs-on: ubuntu-latest
    env:
      SIMPLE_SERVICE_HOST: ${{ secrets.SIMPLE_SERVICE_HOST }}
    needs: [terraform]
    defaults:
      run:
        working-directory: ./3-SimpleService/test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - name: Run tests
        run: |
          go run test.go