name: "Simple Service - Destroy"
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
      SIMPLE_SERVICE_HOST: ${{ secrets.SIMPLE_SERVICE_HOST }}
      PRIVATE_KEY_OUTPUT_FILE: ./simple_service_private_key.pem
    defaults:
      run:
        working-directory: ./3-SimpleService/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform apply -auto-approve -destroy -var="hosted_zone_name=$HOSTED_ZONE_NAME" -var="simple_service_host=$SIMPLE_SERVICE_HOST" -var="executable_jar_path=" -var="private_key_output_file=$PRIVATE_KEY_OUTPUT_FILE"