name: "Simple Service - Deploy"
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./3-SimpleService/todo-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Run tests
        run: mvn clean install
      - name: Find jar
        id: find_jar
        run: echo "EXECUTABLE_JAR_RELATIVE_PATH=$(find `pwd -P`/target -maxdepth 1 -name '*.jar')" >> $GITHUB_OUTPUT
      - name: Upload executable jar
        uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: ${{ steps.find_jar.outputs.EXECUTABLE_JAR_RELATIVE_PATH }}


  terraform:
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
      SIMPLE_SERVICE_HOST: ${{ secrets.API_GATEWAY_HOST }}
      PRIVATE_KEY_OUTPUT_FILE: ./simple_service_private_key.pem
    defaults:
      run:
        working-directory: ./3-SimpleService/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: app.jar
          path: .
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform init
      - name: Terraform Deploy
        run: terraform apply -auto-approve -var="hosted_zone_name=$HOSTED_ZONE_NAME" -var="simple_service_host=$SIMPLE_SERVICE_HOST" -var="executable_jar_path=app.jar" -var="private_key_output_file=$PRIVATE_KEY_OUTPUT_FILE"
      - name: Upload private key
        uses: actions/upload-artifact@v2
        with:
          name: simple_service_private_key.pem
          path: "$PRIVATE_KEY_OUTPUT_FILE"