name: "6. Containerized Service - Destroy"
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
      CONTAINERIZED_APP_HOST: ${{ secrets.CONTAINERIZED_APP_HOST }}
      RDS_PSQL_INSTANCE_IDENTIFIER: ${{ secrets.RDS_PSQL_INSTANCE_IDENTIFIER }}
      RDS_PSQL_MASTER_USERNAME: ${{ secrets.RDS_PSQL_MASTER_USERNAME }}
      RDS_PSQL_MASTER_PASSWORD: ${{ secrets.RDS_PSQL_MASTER_PASSWORD }}
    defaults:
      run:
        working-directory: ./6-ContainerizedServices/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.7"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform apply -auto-approve -destroy -var="hosted_zone_name=$HOSTED_ZONE_NAME" -var="containerized_app_host=$CONTAINERIZED_APP_HOST" -var="task_creation_service_image=0" -var="rds_psql_instance_identifier=$RDS_PSQL_INSTANCE_IDENTIFIER" -var="rds_psql_master_username=$RDS_PSQL_MASTER_USERNAME" -var="rds_psql_master_password=$RDS_PSQL_MASTER_PASSWORD"
