name: "7. Orchestrated Service - Deploy"
on:
  workflow_dispatch:
    branches:
      - master

env:
  # If this is made a secret, then its value will be masked when piped to GITHUB_OUTPUT.
  # Apparently, if the value of a secret appears in any job output then it that the value is masked in the output.
  # For example:
  # - Let's say there's a secret `AWS_DEFAULT_REGION=ap-south-1`
  # - Now let's say the command `terraform output -raw ecr_repository_url` outputs `something.ap-south-1.something`.
  # - If we pipe the output of  `terraform output -raw ecr_repository_url` to `$GITHUB_OUTPUT`, Actions will check if the output contains any secret value, that value will be masked in the ouput.
  # - So $GITHUB_OUTPUT will contain `something.**********.something` rather than `something.ap-south-1.something`,
  AWS_DEFAULT_REGION: "ap-south-1"

jobs:
  # Run rest of terraform
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: ./7-OrchestratedServices/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.7"
      - name: Terraform Init
        run: terraform init
      - name: Terraform Deploy
        run: terraform apply -auto-approve
      - name: Generate Kubeconfig file
        run: aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)
      - name: Upload kubeconfig artifact
        uses: actions/upload-artifact@v3
        with:
          name: kubeconfig
          path: ~/.kube/config