name: Publish Shipping Price API
on:
  push:
    paths:
      - 7-OrchestratedServices/backend/shipping-price-api/**
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./7-OrchestratedServices/backend/shipping-price-api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adopt
          cache: maven
      - name: Publish package
        run: mvn -s ./../../../.github/settings.xml -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
