name: "8. Serverless Architecture - Destroy"
on:
  workflow_dispatch:

jobs:
  backend:
    name: Destroy Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./8-ServerlessArchitecture/terraform/backend
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.7"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy backend
        env:
          TF_VAR_aws_region: ${{ vars.AWS_REGION }}
        run: terraform apply -auto-approve -destroy

  infra:
    name: Destroy Infra
    needs: backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./8-ServerlessArchitecture/terraform/infra
    env:
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      TF_VAR_supabase_region: ${{ vars.SUPABASE_REGION }}
      TF_VAR_supabase_organization_id: ${{ vars.SUPABASE_ORGANIZATION_ID }}
      TF_VAR_supabase_access_token: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      TF_VAR_supabase_database_password: ${{ secrets.RDS_PSQL_MASTER_PASSWORD }}
      TF_VAR_aws_secretsmanager_secret_name: ${{ vars.AWS_SECRETSMANAGER_SECRET_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.7"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy Infra
        run: terraform apply -auto-approve -destroy
