name: "Static Website - Deploy"
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      STATIC_WEBSITE_DOMAIN_NAME: ${{ secrets.STATIC_WEBSITE_DOMAIN_NAME }}
      STATIC_WEBSITE_BUCKET_NAME: ${{ secrets.STATIC_WEBSITE_BUCKET_NAME }}
      STATIC_WEBSITE_ZONE_ID: ${{ secrets.STATIC_WEBSITE_ZONE_ID }}
    defaults:
      run:
        working-directory: ./StaticWebsite/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="domain_name=$STATIC_WEBSITE_DOMAIN_NAME" -var="bucket_name=$STATIC_WEBSITE_BUCKET_NAME" -var="route53_hosted_zone_id=$STATIC_WEBSITE_ZONE_ID"
  publish:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    needs: [terraform]
    defaults:
      run:
        working-directory: ./StaticWebsite
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish Website
        run: |
          aws s3 sync src s3://terraform.w-k-s.io --delete --region $AWS_DEFAULT_REGION