name: "Static Website"
on:
  workflow_dispatch:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: ./StaticWebsite/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="domain_name=ami-abc123" -var="bucket_name=ami-abc123" -var="route53_hosted_zone_id=ami-abc123"
  publish:
    runs-on: ubuntu-latest
    needs: [terraform]
    defaults:
      run:
        working-directory: ./StaticWebsite
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure Kubectl
        run: |
          aws s3 sync src s3://terraform.w-k-s.io --delete --region $AWS_REGION