version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "noticeboarduser"
      POSTGRES_PASSWORD: "noticeboardPassword"
      POSTGRES_DB: "noticeboard"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d